### PR TITLE
Allow cio_id to be used as the identifier on the path

### PR DESCRIPTION
**Pull request by devedup**
This is from the API Docs:

If you want to update identifiers that are already set for a person, you must reference them using their cio_id in the format cio_<cio_id_value>; attempting to update identifier values for a person without referencing them by cio_id will result in an Attribute Update Failure.

### CODE REVIEW

**Comment by krzaczek** [comment]
Hey @devedup thx for the PR. I will look into it by the end of the week

**Comment by devedup** [comment]
That's cool. Turns out I needed to do the same thing in a few other cases, such as triggering events. cio_id is a valid identifier in various places. 👍

**Comment by krzaczek** [comment]
Continue in https://github.com/printu/customerio/pull/48

**Comment by krzaczek** [comment]
Relased in 3.4.0-rc.1

**Pull request closed without merging**
