### PR TITLE
Getter for current instance of the http client

### PR DESCRIPTION
**Pull request by sngrl2**
In my workflow, it will be very useful to be able to get the current http client instance, change some of its settings, and them set it back

### CODE REVIEW

**Comment by sngrl2** [comment]
@krzaczek hey, what can you say?

**Comment by pkrzaczkowski-hippo** [comment]
Well the setDefaultClient creates a default guzzle http client without any modifications. Why would You need to get it to modify it ? Just create Your own GuzzleHttp/Client - set it up and use setClient(). Is there any reason You need the default created by the constructor ?

**Comment by sngrl2** [comment]
In some cases we need to change default Guzzle options after creating, for example connect timeout or user agent, on-the-fly. Yes, we can implement some helper which will return default Guzzle instance with modified options and inject them to the lib via setClient(), but modification already exists object seems like more convinient and optimized, if we need to change only one option.

Do you see any problems with public getter for the client?

**Comment by krzaczek** [comment]
@sngrl2 nope just wanted to know the context

**Pull request merged**
